- name: Collect facts
  hosts: tag_Ansible_Blue:tag_Ansible_Green
  tasks: []

- name: Switcher configurator
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Generate configure file to Nginx
    blockinfile:
      path: /etc/nginx/conf.d/load-balancer.conf
      insertafter: '(.*)upstream flaskapi {'
      block: |
        {% for host in groups['tag_Ansible_Blue'] %}
                server {{ hostvars[host]['ansible_facts']['eth0']['ipv4']['address'] }}:5000;

        {% endfor %}
  handlers:
  - name: Restart Proxy
    service: name=nginx state=restarted
